"""
Signal 2: LLM-based Classifier.

Sends text to Groq's llama-3.3-70b-versatile and parses a probability +
short rationale out of the response. See planning.md §1 (Signal 2) for
the spec.

The module exposes `analyze_llm(text)` and a `GroqUnavailable` exception
that app.py catches to trigger the stylometric-only fallback path.
"""

import json
import os
import re
from typing import Dict, Any

from groq import Groq
from dotenv import load_dotenv

load_dotenv()


class GroqUnavailable(Exception):
    """Raised when Groq cannot be reached or returns unusable output.

    app.py catches this and falls back to stylometric-only with the
    verdict tier forced to 'uncertain' per planning.md §1.
    """


# Module-level client, lazily initialized.
_client = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise GroqUnavailable("GROQ_API_KEY not set in environment")
        _client = Groq(api_key=api_key)
    return _client


# Prompt strategy from planning.md §1 Signal 2:
#   - return JSON with `score` and `rationale` only
#   - anchor at 0.0 (clearly human), 0.5 (genuinely undetermined), 1.0 (clearly AI)
#   - refuse to refuse: short or ambiguous input → 0.5, not an error
SYSTEM_PROMPT = """You are a text-provenance analyzer. Your job is to assess \
whether a piece of writing was likely written by a human or generated by an \
AI language model.

Respond ONLY with a single JSON object, no surrounding prose or markdown:
{"score": <float between 0.0 and 1.0>, "rationale": "<one short sentence>"}

Scoring anchors:
- 0.0 — clearly human (idiosyncratic voice, varied rhythm, natural imperfections)
- 0.5 — genuinely ambiguous; you cannot tell from the available text
- 1.0 — clearly AI-generated (uniform phrasing, generic vocabulary, formulaic transitions)

Do NOT refuse to answer. If the text is short, ambiguous, in another language, \
or otherwise hard to judge, return 0.5 with a rationale explaining why."""


def _extract_json(raw: str) -> str:
    """
    Best-effort JSON extraction.

    LLMs sometimes wrap JSON in markdown code fences or add a polite preamble
    despite being told not to. We try a code fence first, then fall back to
    grabbing the outermost { ... } block.
    """
    fence = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if fence:
        return fence.group(1)
    brace = re.search(r"(\{.*\})", raw, re.DOTALL)
    if brace:
        return brace.group(1)
    raise GroqUnavailable(f"could not locate JSON in LLM response: {raw[:120]!r}")


def analyze_llm(text: str) -> Dict[str, Any]:
    """
    Run the LLM classifier on `text`.

    Returns:
        {
            "score":     float in [0, 1],   # higher = more AI-like
            "rationale": str,                # short reasoning from the model
        }

    Raises:
        GroqUnavailable: API key missing, network error, parse failure, etc.
    """
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.0,   # deterministic for reproducible audit logs
            max_tokens=200,
        )
        raw = response.choices[0].message.content or ""
    except GroqUnavailable:
        raise
    except Exception as e:
        # Network / auth / rate-limit / etc.
        raise GroqUnavailable(f"Groq API call failed: {type(e).__name__}: {e}")

    try:
        parsed = json.loads(_extract_json(raw))
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))   # clip defensively
        rationale = str(parsed.get("rationale", ""))[:300]
    except (json.JSONDecodeError, ValueError, TypeError) as e:
        raise GroqUnavailable(f"failed to parse LLM JSON ({e}): {raw[:120]!r}")

    return {
        "score": round(score, 3),
        "rationale": rationale,
    }
